import type { Metadata } from 'next'
import { Providers } from './providers'
import { PageContainer } from '@/modules/common/PageContainer'

export const metadata: Metadata = {
    title: 'React Frontend Challenge',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <PageContainer>{children}</PageContainer>
                </Providers>
            </body>
        </html>
    )
}
